apiVersion: skaffold/v2alpha3
kind: Config
deploy: 
  kubectl: 
    manifests: 
      - ./infra/k8s/*
build:
  local:  
    push: false 
  artifacts: 
    - image: thakkarpanth/auth
      context: auth
      docker: 
        dockerfile: Dockerfile
      sync: 
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: thakkarpanth/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .        
    - image: stephengrider/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: thakkarpanth/orders
      context: orders
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
        